/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latex_assignment;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Void
 */
public class SectionScreen extends javax.swing.JFrame {

    public SectionScreen() {
        initComponents();
        l = Latex_Assignment.GetInstance();
        SectionName.requestFocusInWindow();
        FillCurrentSection();
    }

    public SectionScreen(Latex_Assignment a) {
        initComponents();
        l = a;
        SectionName.requestFocusInWindow();
        FillCurrentSection();
    }
    Latex_Assignment l;
    JFrame f = new JFrame();

    private void FillCurrentSection() {
        document.setText(l.GetLatex());
        if (l.GetSection() == 0) {
            currentSection.setText("No Section");
        } else if (l.GetSection() == 1) {
            currentSection.setText("Section");
        } else {
            currentSection.setText("Sub Section");
        }
    }

    private void ExitProgram() {
        WindowEvent w = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(w);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        BackgroundPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        next = new javax.swing.JButton();
        currentSection = new java.awt.Label();
        label7 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        SectionName = new javax.swing.JTextField();
        SubSectionName = new javax.swing.JTextField();
        AddSection = new javax.swing.JButton();
        AddSubSection = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        document = new javax.swing.JTextArea();
        SAVE = new javax.swing.JButton();
        END = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LATEX CONVERTER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BackgroundPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 70));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));

        next.setBackground(new java.awt.Color(0, 102, 153));
        next.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("NEXT");
        next.setActionCommand("");
        next.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        next.setContentAreaFilled(false);
        next.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        next.setOpaque(true);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        currentSection.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N

        label7.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        label7.setText("Current Writing Section Type:");

        label3.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        label3.setText("Section Name:");

        label4.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        label4.setText("Sub Section Name:");

        SectionName.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, SubSectionName, org.jdesktop.beansbinding.ObjectProperty.create(), SectionName, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        SectionName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectionNameActionPerformed(evt);
            }
        });

        SubSectionName.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, SectionName, org.jdesktop.beansbinding.ObjectProperty.create(), SubSectionName, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        SubSectionName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubSectionNameActionPerformed(evt);
            }
        });

        AddSection.setBackground(new java.awt.Color(0, 102, 153));
        AddSection.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        AddSection.setForeground(new java.awt.Color(255, 255, 255));
        AddSection.setText("ADD");
        AddSection.setActionCommand("");
        AddSection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AddSection.setContentAreaFilled(false);
        AddSection.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        AddSection.setOpaque(true);
        AddSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSectionActionPerformed(evt);
            }
        });

        AddSubSection.setBackground(new java.awt.Color(0, 102, 153));
        AddSubSection.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        AddSubSection.setForeground(new java.awt.Color(255, 255, 255));
        AddSubSection.setText("ADD");
        AddSubSection.setActionCommand("");
        AddSubSection.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AddSubSection.setContentAreaFilled(false);
        AddSubSection.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        AddSubSection.setOpaque(true);
        AddSubSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSubSectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SubSectionName, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                    .addComponent(SectionName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(331, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(329, 329, 329))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(AddSection, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(AddSubSection, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(currentSection, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(487, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(currentSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SectionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(AddSection, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubSectionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(AddSubSection, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(713, Short.MAX_VALUE)))
        );

        BackgroundPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 860, 830));

        document.setColumns(20);
        document.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        document.setLineWrap(true);
        document.setRows(5);
        document.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 77, 64), 1, true));
        jScrollPane1.setViewportView(document);

        BackgroundPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 750, 820));

        SAVE.setBackground(new java.awt.Color(0, 102, 153));
        SAVE.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        SAVE.setForeground(new java.awt.Color(255, 255, 255));
        SAVE.setText("SAVE DOCUMENT");
        SAVE.setActionCommand("");
        SAVE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        SAVE.setContentAreaFilled(false);
        SAVE.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        SAVE.setOpaque(true);
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        BackgroundPanel.add(SAVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 830, 280, 60));

        END.setBackground(new java.awt.Color(0, 102, 153));
        END.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        END.setForeground(new java.awt.Color(255, 255, 255));
        END.setText("END DOCUMNET");
        END.setActionCommand("");
        END.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        END.setContentAreaFilled(false);
        END.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        END.setOpaque(true);
        END.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENDActionPerformed(evt);
            }
        });
        BackgroundPanel.add(END, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 830, 270, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        if (l.GetSection() == 0) {
            JOptionPane.showMessageDialog(f, "Cannot proceed until a Section is added", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            this.setVisible(false);
            WritingScreen abc = new WritingScreen(l);
            abc.setVisible(true);
        }
    }//GEN-LAST:event_nextActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // TODO add your handling code here:
        if (document.getText().equals("")) {
            JOptionPane.showMessageDialog(f, "Missing Value, Document is empty", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {

            l.SetLatex(document.getText());
            JOptionPane.showMessageDialog(f, "Document Saved");
        }
    }//GEN-LAST:event_SAVEActionPerformed

    private void ENDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENDActionPerformed
        // TODO add your handling code here:
        l.EndDocument();
        JOptionPane.showMessageDialog(f, "Document ended successfully");
        this.setVisible(false);
        ExitProgram();
    }//GEN-LAST:event_ENDActionPerformed

    private void SectionNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectionNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SectionNameActionPerformed

    private void SubSectionNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubSectionNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubSectionNameActionPerformed

    private void AddSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSectionActionPerformed
        if (SectionName.getText().equals("")) {
            JOptionPane.showMessageDialog(f, "Missing Value, Enter Section Name", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            l.StartSection(SectionName.getText());
            JOptionPane.showMessageDialog(f, "Section Started");
            l.SetSection(1);
            document.setText(l.GetLatex());
            SectionName.setText("");
            SubSectionName.setText("");
        }
    }//GEN-LAST:event_AddSectionActionPerformed

    private void AddSubSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSubSectionActionPerformed
        // TODO add your handling code here:
        if (SubSectionName.getText().equals("")) {
            JOptionPane.showMessageDialog(f, "Missing Value, Enter Sub Section Name", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (l.GetSection() == 0) {
            JOptionPane.showMessageDialog(f, "Cannot Add Sub Section before a Section", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            l.SetSection(2);
            l.StartSubSection(SubSectionName.getText());
            JOptionPane.showMessageDialog(f, "Sub Section Started");
            document.setText(l.GetLatex());
            SectionName.setText("");
            SubSectionName.setText("");
        }
    }//GEN-LAST:event_AddSubSectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        JFrame newMain = new SectionScreen();
        newMain.setVisible(true);
        newMain.setResizable(false);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSection;
    private javax.swing.JButton AddSubSection;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JButton END;
    private javax.swing.JButton SAVE;
    private javax.swing.JTextField SectionName;
    private javax.swing.JTextField SubSectionName;
    private java.awt.Label currentSection;
    private javax.swing.JTextArea document;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label7;
    private javax.swing.JButton next;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
